# Generated by Django 4.0.3 on 2022-04-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='slug',
        ),
    ]
