# Generated by Django 4.0.3 on 2022-04-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_articulo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
